### ISSUE TITLE
Error: package oracle.dbtools.worksheet.editor does not exist	SQLMemoInsertController.java

### ISSUE THREAD

**Issue by ngxhe** [scristalli/SQLMemo#4]
Follow your instruction, when I run JAR_Deloy, it show error as capture below.

![capture](https://user-images.githubusercontent.com/14900191/32821897-764088aa-ca08-11e7-97ea-0946e16ca61e.JPG)

This is my environment:
  - JDeveloper Java Edition Version 12.2.1.3.0 (Build JDEVADF_12.2.1.PATCHSETS_GENERIC_170820.0914.S)
  - Java 8 (1.8.0.40)
  - SQLMemo-master.zip
  - Extension SDK 12.2.1.3.42.170820.0914 (http://www.oracle.com/webfolder/technetwork/jdeveloper/downloads/1213center.xml#oracle.jdeveloper.esdk)

Please check and help me this case !

**Comment by nguyenewb** [comment]
I found and add *jar file from folder: sqldeveloper-4.2.0.17.089.1709\sqldeveloper\extensions\*.jar
By the way, I share the link that help me to run debug, using debug remote (http://www.databaseusers.com/article/9620431/Extension+development+-+how+to+debug%3F)
Hope it helpful ! ^^
