### ISSUE TITLE
Query location

### ISSUE THREAD

**Issue by ohuanasis** [scristalli/SQLMemo#6]
Where does sql memo saved the queries in case i need to back up all.

**Comment by scristalli** [comment]
Hello, this is the location of the file sqlmemo.conf:
`String file_path = Ide.getUserSettingsDirectory() + File.separator + "sqlmemo.conf";`

So it should be in a directory under your IDE tree, just grep its name.

**Comment by ohuanasis** [comment]
Great thanks.
